import { Col, Row } from "antd";
import { styles } from "./globals";
import {
    FaClipboardList,
    FaMobile,
    FaClipboardCheck,
    FaBullseye,
    FaRecycle,
    FaLightbulb,
    FaBolt,
    FaCogs
} from 'react-icons/fa'
import { IconContext } from "react-icons/lib";

const advantageList = {
    advantageOne: {
        name: "Adaptive",
        description: 'Our app continuously evolves its workout programs to better suit the users\' needs. It also adapts to sudden changes of a user\'s lifestyle.',
        image: <FaRecycle />
    },
    advantageTwo: {
        name: "Accurate",
        description: 'We have a special feature of targeted muscle training without sacrificing the users\' overall build composition. This feature is for those who aim to have spectacular results over a specific muscle build.',
        image: <FaBullseye />
    },
    advantageThree: {
        name: "Consistent",
        description: 'We provide the same intensity for the workout programs of the user over the course of their plan.',
        image: <FaClipboardList />
    },
    advantageFour: {
        name: "Convenient",
        description: 'We value our users\' time and ultimately their lifestyle, so SpeccUp offers convenience by being accessible through your mobile phones',
        image: <FaMobile />
    },
    advantageFive: {
        name: "Effective",
        description: 'The workout plans generated by our app is generally intended to be followed for only 3 months. Even if the user skips a few days, they would still look like what they saw during the plans onboarding.',
        image: <FaCogs />
    },
    advantageSix: {
        name: "Efficient",
        description: 'Intense progression of the workout plans made by our app enable users to fully maximize and utilize their environment and even themselves during workout.',
        image: <FaBolt />
    },
    advantageSeven: {
        name: "Results",
        description: 'SpeccUp delivers timely and invaluable results. When our app says that the user would have gains in the course of their plan, they would, even if they don\'t follow the plan to the letter.',
        image: <FaClipboardCheck />
    },
    advantageEight: {
        name: "Smart",
        description: 'SpeccUp asks for your necessary details to be able to generate workout plans. Our app has the advantage of formulating a number of possible workout plans even with the inclusion of the users\' allergies and disabilities.',
        image: <FaLightbulb />
    },
}

const Advantages = () => {
    return (
        <Row 
            style={{
                backgroundColor: '#277DCD',
                justifyContent: 'center',
                paddingBottom: '64px'
            }}
        >
            <Col span={24}>
                <p style={{ ...styles.homeHeader, color: 'white' }}>Advantages</p>
            </Col>
            <Col span={16}>
                <Row justify="center" gutter={[64, 48]}>
                    {Object.keys(advantageList).map((advantage, index) => (
                        <Col
                            key={index} 
                            xs={{ span: 24 }}
                            sm={{ span: 20 }}
                            md={{ span: 12 }}
                            lg={{ span: 10 }}
                            xxl={{ span: 7 }}
                        >
                            <IconContext.Provider
                                value={{
                                    style: {
                                        width: '48px',
                                        height: '48px',
                                        color: '#FFBF00'
                                    }
                                }}
                            >
                                <div>
                                    {advantageList[advantage].image}
                                </div>
                            </IconContext.Provider>
                            <p style={styles.advantage.name}>{advantageList[advantage].name}</p>
                            <p style={styles.advantage.description}>{advantageList[advantage].description}</p>
                        </Col>
                    ))}
                </Row>
            </Col>
        </Row>
    );
};

export default Advantages;